// Similar to C or C++, we have various conditional statements and loops in JS
// But, there are some other features in loops which seems quiet familiar to python 

/** if
 *  if else
 * if else if
 * if else if else if .........
 * switch
 */

// see some conditional statements


let a = 10
let b = 20

/* 

if(a>b){
    console.log(a,' is greater than ',b)
}

if(a<b){
    console.log(a,' is smaller than ',b)
}

else if(a==b){
    console.log(a,' is equal to ',b)
}

else{
    console.log(a,' is not greater than  ',b)
}

*/


// ----------------------switch statement----------------

/*

switch (expression) {
    case choice1:
      // run this code
      break;
  
    case choice2:
      // run this code instead
      break;
  
    // include as many cases as you like
  
    default:
      // actually, just run this code
      break;
  }

*/


// -------------Ternary operator--------------

/*

let c = (a>b) ? "greater" : "smaller" ;
console.log(c);

*/