let myDate = new Date()
// console.log(myDate.toISOString())
// console.log(myDate.toDateString())
// console.log(myDate.toJSON())
// console.log(myDate.toLocaleDateString())
// console.log(myDate.toString())
// console.log(myDate.toTimeString())
// console.log(myDate.toUTCString())

console.log(myDate.getDate());

// for timeStamps :
console.log(Date.now());

console.log(myDate.getHours())
// explore more ..

