// some string format in Js is discussed below:
// You can know about all string format function in web's Js

// const sentence = "The quick brown fox jumps over the lazy dog.";

// console.log(sentence.toLowerCase());
// // Expected output: "the quick brown fox jumps over the lazy dog."

const name = "DaVid";

console.log(name.length);

console.log(`My name is ${name}.`);

console.log(name.toUpperCase());

console.log(name.toLowerCase());

console.log(name.charAt(4));

console.log(name.indexOf('v'));

console.log(name.bold());

console.log(name.endsWith('David'));